linters:
  disable-all: true
  enable:
    - depguard
    - dupl
    - durationcheck
    - exhaustive
    - exportloopref
    - gci
    - gocritic
    - godot
    - goimports
    - gomoddirectives
    - importas
    - ineffassign
    - makezero
    - misspell
    - nakedret
    - nilerr
    - prealloc
    - predeclared
    - revive
    - stylecheck
    - paralleltest
    - tparallel
    - unconvert
    - unparam
    - unused
    - wastedassign
    - whitespace
linters-settings:
  depguard:
    rules:
      main:
        files:
          - $all
          - "!$test"
        allow:
          - $gostd
        deny:
      test:
        files:
          - $test
        allow:
          - $gostd
          - "github.com/ivanrad/base62"
        deny:
