name: base62 CI

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    strategy:
      matrix:
        go: [1.17, 1.18, 1.19]

    steps:
    - name: Set up Go
      uses: WillAbides/setup-go-faster@v1.8.0
      with:
        go-version: ${{ matrix.go }}

    - name: Checkout
      uses: actions/checkout@v3

    - name: "go: build"
      run: make build

    - name: "go: test"
      run: make test

    - name: "go: vet"
      run: make vet

    - name: "go: gofmt"
      run: make gofmt

    - name: "go: staticcheck"
      uses: dominikh/staticcheck-action@v1.3.0
      with:
        version: "2022.1.3"

    - name: "go: golangci-lint"
      uses: golangci/golangci-lint-action@v3
      with:
        version: latest
        skip-build-cache: true
        skip-pkg-cache: true
